### ISSUE TITLE
Consul service name should be `nim-waku`

### ISSUE THREAD

**Issue by yakimant** [status-im/infra-role-nim-waku#21]
Currently we have:
- nim-waku-store
- nim-waku-boot
- nim-waku-v2
- nim-waku

for both both consul service name and id.

Let's have like `beacon-node` - same name, but different id's:
https://consul.infra.status.im/ui/ih-eu-mda1/services/beacon-node

See in code:
https://github.com/status-im/infra-role-beacon-node-linux/blob/3642b4b5ca13b0a637670c870df1d312e8ff5d99/tasks/consul.yml#L20-L21

https://github.com/status-im/infra-role-beacon-node-linux/blob/3642b4b5ca13b0a637670c870df1d312e8ff5d99/defaults/main.yml#L105-L107

Probably for all `nim-waku-*` service (`-enr`, `-rpc`,..).
Please check the scripts relying on service names, eg fleets.json generation, enrtrees generation and cabot checks. They might be changed.

**Comment by yakimant** [comment]
@jakubgs, shall we remove `-boot`, `-store`, `-v2` from all services (`-enr`, `-rpc`, `-metrics`). I think so - would be much better.

**Comment by yakimant** [comment]
Requires an updates:
- https://github.com/status-im/infra-misc/blob/master/ansible/roles/status-fleets/files/eth_fleet_json.py

**Comment by jakubgs** [comment]
Or we could just improve `collect_fleets()` to support an optional argument of `service_id`.

We'd need to make the structure more complex, but it seems better than using metadata.

**Comment by jakubgs** [comment]
>shall we remove -boot, -store, -v2 from all services

Yes, that's the idea.

**Comment by jakubgs** [comment]
For `collect_fleets()` I imagine something more like:
```python
    # shards.* fleets
    fleets.update(collect_fleets('shards', {
        'tcp/p2p/waku/boot':  { name: 'nim-waku', id: 'nim-waku-boot' },
        'enr/p2p/waku/boot':  { name: 'nim-waku', id: 'nim-waku-boot-enr' },
        'tcp/p2p/waku/store': { name: 'nim-waku', id: 'nim-waku-store' },
        'enr/p2p/waku/store': { name: 'nim-waku', id: 'nim-waku-store-enr' },
    }))
```
Where `id` is optional. Just an idea. If we wanted to be fancy we'd have a class for that:
```python
        'enr/p2p/waku/boot':  ServiceQuery(name: 'nim-waku', id: 'nim-waku-boot-enr'),
```

**Comment by jakubgs** [comment]
One more thing I realized, is that `dnsdisc.py` in `infra-utils` will need to be updated to accept a service ID as well:
https://github.com/status-im/infra-utils/blob/34e5d068a46c408426b7b6c4182f1ab828632528/consul/dnsdisc.py#L177-L186

**Comment by yakimant** [comment]
Yes, you are right, my previous analysis was incorrect.
I thought service name is enough, but we need different record for boot and store nodes.

**Comment by jakubgs** [comment]
But we can achieve that with just service id difference. That's enough. Service name can be common across all.

**Comment by yakimant** [comment]
https://github.com/status-im/infra-misc/pull/210 for `eth_fleet_json.py`

**Comment by yakimant** [comment]
As I see from the code, which you shared, multiple query services are supported for `dnsdisc.py`.

I didn't try it though.

Options to support new `service_id` query:
1. Remove multiple service option, so you run `dnsdisc.py` multiple times for each service_name : service_id pair. For example `service_name:nim_waku` and `service_id:nim-waku-boot`
2. Remove multiple `service_name` option, but add multiple `service_id` option. So you can run for example with service_name:nim_waku and service_ids:nim-waku-boot, nim-waku-store.
3. Support quering multiple services by `service_name`. Question will be, how to specify (or leave empy) `service_id` (or `service_ids`) for eachn `service_name`

My personal preference is 1.

@jakubgs, what do you think?

**Comment by yakimant** [comment]
https://github.com/status-im/infra-utils/pull/6 for `dnsdisc.py`

**Comment by yakimant** [comment]
Updated waku, shards and waku-v2 repos and fleet.

Looks beautiful now:
![Screenshot 2023-12-29 at 17 41 05](https://github.com/status-im/infra-role-nim-waku/assets/1529006/19507b8f-913a-44af-b45b-01393f605ba4)
![Screenshot 2023-12-29 at 17 41 51](https://github.com/status-im/infra-role-nim-waku/assets/1529006/5d2c1929-5ddc-4a7e-be36-747d47a1eb07)

**Comment by yakimant** [comment]
What's left:
- [ ] update status repo and fleet
- [ ] chec dnsdisc works well on production consul
- [ ] check grafana graphs available

**Comment by jakubgs** [comment]
Looking good.
